name: Validate changes
on: workflow_dispatch
jobs:
  validate:
    runs-on: self-hosted
    name: Validate terraform configuration
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: terraform validate
        uses: dflook/terraform-validate@v1
        with:
          path: terraform
